server:
  port: 8501

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/
spring:
  cassandra:
    contact:
      point: localhost
    port: 9042
    keyspace:
      name: springcloud
    username: cassandra
    password: cassandra


